id: P8ECFCA57
initial_creation_type: ocr
source_metadata:
  volumes:
    7162bf4f42874e82b12d609c822ae5f0:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
